[package]
name = "libz-ng-sys"
version = "1.1.14"
authors = [
    "Alex Crichton <alex@alexcrichton.com>",
    "Josh Triplett <josh@joshtriplett.org>",
    "Sebastian Thiel <sebastian.thiel@icloud.com>",
]
links = "z-ng"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang/libz-sys"
description = "Low-level bindings to zlib-ng (libz-ng), a high-performance zlib library."
categories = ["compression", "external-ffi-bindings"]
keywords = ["zlib", "zlib-ng"]
edition = "2018"

exclude = [
    "/.github",
    "/.gitmodules",
    "/README.md",
    "/build.rs",
    "/cargo-zng",
    "/ci",
    "/src/smoke.c",
    "/src/zlib",
    "/systest",
]

build = "build_zng.rs"
readme = "README-zng.md"

[workspace]
members = ["systest"]

[dependencies]
libc = "0.2.43"

[build-dependencies]
cc = "1.0"
